### ISSUE TITLE
Optional fall-back to local fulltext search when the keywords are not available?

### ISSUE THREAD

**Issue by WoLpH** [Kapeli/feeds#7]
This issue is not specific to Ansible, but it's the place where it bugs me the most :)

When using Ansible I regularly use loops and such, the thing is that within the code these look like this:

(example from the docs)
```
tasks:
  - name: Print phone records
    debug: msg="User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
    with_dict: users
```

Where the `with_dict` is the actual loop, the same goes for things like `with_nested`, `with_items` and more. When looking for those within Dash you get no results at all, only when looking for `Loops` will Dash give you the results.

I know the Ansible docs aren't too easily indexable for tools like Dash, but there should be a slightly better approach here.

Possible options:
 - Add local fulltext search when no results are found
 - Allow people to add aliases to items

**Comment by Kapeli** [comment]
> Add local fulltext search when no results are found

I haven't really seen a need for this. I do have plans to add it though, just not a huge priority. The main issue is how to differentiate interface-wise between regular results and FTS results.

> Allow people to add aliases to items

My approach to Dash is to not overcomplicate things. I don't want users to have to add stuff. I'd much rather have users complain about missing stuff so that I can fix it somehow.
