### ISSUE TITLE
private feeds and .tarix files

### ISSUE THREAD

**Issue by d9pouces** [Kapeli/feeds#9]
Hi,

I'm not sure if this is the best place to ask the question, but it is related to Dash feeds, so…

I want to setup a private docket feed server, and I carefully read your doc at https://kapeli.com/docsets .
However, when a I try to use my feed in Dash, I have these requests: 

  * GET docset-9/Python-3.6.0.xml 
  * GET docset-9.tgz
  * HEAD docset-9.tgz.tarix
  * GET docset-9.tgz.tarix

What is this .tarix file? I can download http://sanfrancisco.kapeli.com/feeds/Django.tgz.tarix , but I am unable to discover its format or nature (excepting that is a gzip file). Could you give more info?

**Comment by Kapeli** [comment]
Does Dash fail to install the docset because of that? It should normally stop at the `HEAD docset-9.tgz.tarix` request, and not proceed to the `GET` if the file doesn't exist.

The `tarix` files are for Dash's compressed docsets feature (i.e. Dash keeps the docsets compressed and reads the doc pages from the archives directly). These are not supported for private feeds currently.

**Comment by d9pouces** [comment]
Thanks for the explanation.
The bug was in my docset (invalid because the archive was not properly closed during the generation), Dash could not install my private docset and I thought to .tarix files. Now, everything works fine.

You can closed this bug.
